package br.ufc.meadds.entity;

// Generated 01/06/2011 09:36:02 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

// TODO: Auto-generated Javadoc
/**
 * Algorithmtype generated by hbm2java.
 */
@Entity
@Table(name = "algorithm_type", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class AlgorithmType implements java.io.Serializable {

	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = -7588528836286238065L;

	/** The id. */
	private Long id;

	/** The name. */
	private String name;

	/** The algorithms. */
	private Set<Algorithm> algorithms = new HashSet<Algorithm>(0);

	/**
	 * Instantiates a new algorithm type.
	 */
	public AlgorithmType() {
	}

	/**
	 * Instantiates a new algorithm type.
	 * 
	 * @param name the name
	 */
	public AlgorithmType(String name) {
		this.name = name;
	}

	/**
	 * Instantiates a new algorithm type.
	 * 
	 * @param name the name
	 * @param algorithms the algorithms
	 */
	public AlgorithmType(String name, Set<Algorithm> algorithms) {
		this.name = name;
		this.algorithms = algorithms;
	}

	/**
	 * Gets the id.
	 * 
	 * @return the id
	 */
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	/**
	 * Sets the id.
	 * 
	 * @param idAlgorithmType the new id
	 */
	public void setId(Long idAlgorithmType) {
		this.id = idAlgorithmType;
	}

	/**
	 * Gets the name.
	 * 
	 * @return the name
	 */
	@Column(name = "name", unique = true, nullable = false, length = 45)
	@NotNull
	@Length(max = 45)
	public String getName() {
		return this.name;
	}

	/**
	 * Sets the name.
	 * 
	 * @param name the new name
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Gets the algorithms.
	 * 
	 * @return the algorithms
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "type")
	public Set<Algorithm> getAlgorithms() {
		return this.algorithms;
	}

	/**
	 * Sets the algorithms.
	 * 
	 * @param algorithms the new algorithms
	 */
	public void setAlgorithms(Set<Algorithm> algorithms) {
		this.algorithms = algorithms;
	}

}
