package br.ufc.meadds.entity;

// Generated 01/06/2011 09:36:02 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

// TODO: Auto-generated Javadoc
/**
 * Application generated by hbm2java.
 */
@Entity
@Table(name = "application", uniqueConstraints = { @UniqueConstraint(columnNames = {
		"name", "version", "library_id", "user_id" }) })
public class Application implements Serializable {

	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 8599894961616999868L;

	/** The id. */
	private Long id;

	/** The version. */
	private Long version;

	/** The library. */
	private Library library;

	/** The user. */
	private User user;

	/** The confidentiality degree. */
	private ConfidentialityDegree confidentialityDegree;

	/** The name. */
	private String name;

	/**
	 * Instantiates a new application.
	 */
	public Application() {
	}

	/**
	 * Instantiates a new application.
	 * 
	 * @param library
	 *            the library
	 * @param user
	 *            the user
	 * @param confidentialityDegree
	 *            the confidentiality degree
	 * @param name
	 *            the name
	 */
	public Application(Library library, User user,
			ConfidentialityDegree confidentialityDegree, String name) {
		this.library = library;
		this.user = user;
		this.confidentialityDegree = confidentialityDegree;
		this.name = name;
	}

	/**
	 * Gets the id.
	 * 
	 * @return the id
	 */
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	/**
	 * Sets the id.
	 * 
	 * @param id
	 *            the new id
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Gets the version.
	 * 
	 * @return the version
	 */
	@Version
	@Column(name = "version", unique = true, nullable = false)
	public Long getVersion() {
		return this.version;
	}

	/**
	 * Sets the version.
	 * 
	 * @param version
	 *            the new version
	 */
	public void setVersion(Long version) {
		this.version = version;
	}

	/**
	 * Gets the library.
	 * 
	 * @return the library
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "library_id", nullable = false)
	@NotNull
	public Library getLibrary() {
		return this.library;
	}

	/**
	 * Sets the library.
	 * 
	 * @param library
	 *            the new library
	 */
	public void setLibrary(Library library) {
		this.library = library;
	}

	/**
	 * Gets the user.
	 * 
	 * @return the user
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	@NotNull
	public User getUser() {
		return this.user;
	}

	/**
	 * Sets the user.
	 * 
	 * @param user
	 *            the new user
	 */
	public void setUser(User user) {
		this.user = user;
	}

	/**
	 * Gets the confidentiality degree.
	 * 
	 * @return the confidentiality degree
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "confidentiality_drgree_id", nullable = false)
	@NotNull
	public ConfidentialityDegree getConfidentialityDegree() {
		return this.confidentialityDegree;
	}

	/**
	 * Sets the confidentiality degree.
	 * 
	 * @param confidentialitydegree
	 *            the new confidentiality degree
	 */
	public void setConfidentialityDegree(
			ConfidentialityDegree confidentialitydegree) {
		this.confidentialityDegree = confidentialitydegree;
	}

	/**
	 * Gets the name.
	 * 
	 * @return the name
	 */
	@Column(name = "name", unique = true, nullable = false, length = 45)
	@NotNull
	@Length(max = 45)
	public String getName() {
		return this.name;
	}

	/**
	 * Sets the name.
	 * 
	 * @param name
	 *            the new name
	 */
	public void setName(String name) {
		this.name = name;
	}

}
